SELECT	D.DISTRICT_NAME "DISTRICT NAME", EXTRACT(YEAR 
FROM	S.TRAN_DATE) "YEAR",
EXTRACT(MONTH 
FROM	S.TRAN_DATE) "MONTH" ,SUM(S.MKB_REV_AMT) "30 DAYS REVENUE"
FROM	
universal_schema.LOCATION L, universal_schema.ASSOCIATE A, universal_schema.SALES_TRANSACTION S,
		universal_schema.DISTRICT D
WHERE	
S.TRAN_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
	AND	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	L.DISTRICT_CD = D.DISTRICT_CD
ORDER	BY "30 DAYS REVENUE" DESC
GROUP	BY D.DISTRICT_NAME, "YEAR", "MONTH"