SELECT	CAST(COUNT(*) AS FLOAT) AS "_twm_cnt"	,CAST(SUM( 
CASE	WHEN "TRAN_DATE" IS NULL THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_null1"	,CAST(SUM( 
CASE	WHEN "SALES_TRAN_ID" IS NULL THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_null2"	,CAST(SUM( 
CASE	WHEN "SALES_TRAN_ID" = 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_zero2"	,CAST(SUM( 
CASE	WHEN "SALES_TRAN_ID" > 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_pos2"	,CAST(SUM( 
CASE	WHEN "SALES_TRAN_ID" < 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_neg2"	,CAST(SUM( 
CASE	WHEN "MKB_COST_AMT" IS NULL THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_null3"	,CAST(SUM( 
CASE	WHEN "MKB_COST_AMT" = 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_zero3"	,CAST(SUM( 
CASE	WHEN "MKB_COST_AMT" > 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_pos3"	,CAST(SUM( 
CASE	WHEN "MKB_COST_AMT" < 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_neg3"	,CAST(SUM( 
CASE	WHEN "MKB_ITEM_QTY" IS NULL THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_null4"	,CAST(SUM( 
CASE	WHEN "MKB_ITEM_QTY" = 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_zero4"	,CAST(SUM( 
CASE	WHEN "MKB_ITEM_QTY" > 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_pos4"	,CAST(SUM( 
CASE	WHEN "MKB_ITEM_QTY" < 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_neg4"	,CAST(SUM( 
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" IS NULL THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_null5"	,CAST(SUM( 
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" = 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_zero5"	,CAST(SUM( 
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" > 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_pos5"	,CAST(SUM( 
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" < 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_neg5"	,CAST(SUM( 
CASE	WHEN "MKB_REV_AMT" IS NULL THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_null6"	,CAST(SUM( 
CASE	WHEN "MKB_REV_AMT" = 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_zero6"	,CAST(SUM( 
CASE	WHEN "MKB_REV_AMT" > 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_pos6"	,CAST(SUM( 
CASE	WHEN "MKB_REV_AMT" < 0 THEN 1.0E0 
ELSE	0.0E0 
END	) AS FLOAT) AS "_twm_neg6"
FROM	"universal_schema"."SALES_TRANSACTION"
WHERE	TRAN_DATE < '2005-10-10'