SELECT	"_twm_bin1"	,"_twm_bin2"	,MIN("Location") AS "_twm_beg1"	,MIN("SALES_TRAN_ID") AS "_twm_beg2"	,MAX("Location") AS "_twm_end1"	,MAX("SALES_TRAN_ID") AS "_twm_end2"	,CAST(COUNT(*) AS FLOAT) AS "_twm_cnt"
FROM	(
SELECT	CASE 
	WHEN	"Location" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "Location" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "Location") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "Location" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin1"	,
CASE	WHEN "SALES_TRAN_ID" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "SALES_TRAN_ID" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "SALES_TRAN_ID") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "SALES_TRAN_ID" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin2"	,"Location"	,"SALES_TRAN_ID"
FROM	"universal_schema"."sales_transaction_line"
) AS "T1"
GROUP	BY 1,2