SELECT	L.LOCATION_NAME "STORE NAME", L.LOCATION_TOTAL_AREA_MEAS "SIZE",
		COUNT(P.PARTY_ID) "NUMOFCUSTOMERS",(COUNT(P.PARTY_ID)(DECIMAL(18,
		2))) / L.LOCATION_TOTAL_AREA_MEAS (DECIMAL(18,2)) "#OFCUSTOMERS PER FOOT"
FROM	universal_schema.PARTY P, universal_schema.LOCATION L
WHERE	
SUBSTR(TRIM(P.PARTY_ID),1,3) = L.LOCATION_ID
GROUP	BY 1,2
ORDER	BY "#OFCUSTOMERS PER FOOT" DESC