SELECT	A.NAME "STORE NAME", A.REFUNDED "AVE OF 18 MONTHS", B.REFUNDED "30 DAYS",
		(B.REFUNDED * 100 (DECIMAL(18,2)))/ A.REFUNDED (DECIMAL(18,2)) "%"
FROM	
(
SELECT	L.LOCATION_NAME "STORE NAME", SUM(R.Return_Item_Qty * R.Unit_Refund_Amt)/18 "# OF REFUNDED"
FROM	universal_schema.LOCATION L, universal_schema.RETURN_TRANSACTION_LINE R,
		universal_schema.SALES_TRANSACTION_LINE S
WHERE	R.Original_Sales_Tran_Id = S.SALES_TRAN_ID
	AND	S.LOCATION = L.LOCATION_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
GROUP	BY "STORE NAME")A(NAME,REFUNDED),
(
SELECT	L.LOCATION_NAME "STORE NAME", SUM(R.Return_Item_Qty * R.Unit_Refund_Amt) "# OF REFUNDED"
FROM	universal_schema.LOCATION L, universal_schema.RETURN_TRANSACTION_LINE R,
		universal_schema.SALES_TRANSACTION_LINE S
WHERE	R.Original_Sales_Tran_Id = S.SALES_TRAN_ID
	AND	S.LOCATION = L.LOCATION_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2005-06-01'
GROUP	BY "STORE NAME")B(NAME,REFUNDED)
WHERE	A.NAME = B.NAME