SELECT	"_twm_bin1"	,MIN("SALES_TRAN_ID") AS "_twm_beg1"	,MAX("SALES_TRAN_ID") AS "_twm_end1"	,CAST(COUNT(*) AS FLOAT) AS "_twm_cnt"
FROM	(
SELECT	CASE 
	WHEN	"SALES_TRAN_ID" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "SALES_TRAN_ID" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "SALES_TRAN_ID") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "SALES_TRAN_ID" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin1"	,"SALES_TRAN_ID"
FROM	"universal_schema"."SALES_TRANSACTION"
WHERE	TRAN_DATE < '2005-10-10'
) AS "T1"
GROUP	BY 1