SELECT	K.NAME "STORE NAME",K.REV "REVENUE",M.REV "REV FROM OTHERS",
		(K.REV + M.REV) * 100 / M.REV "%"
FROM	
(
SELECT	L.LOCATION_NAME,SUM(S.MKB_REV_AMT)
FROM	universal_schema.LOCATION L, universal_schema.SALES_TRANSACTION S,
		universal_schema.ASSOCIATE A
WHERE	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = SUBSTR(TRIM(S.REWARD_CD),1,3)
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	S.TRAN_DATE BETWEEN '2005-04-01' 
	AND	'2005-06-30'
GROUP	BY L.LOCATION_NAME
)K(NAME,REV),
(
SELECT	L.LOCATION_NAME,SUM(S.MKB_REV_AMT)
FROM	universal_schema.LOCATION L, universal_schema.SALES_TRANSACTION S,
		universal_schema.ASSOCIATE A
WHERE	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID <> SUBSTR(TRIM(S.REWARD_CD),1,3)
	AND	S.REWARD_CD <> ''
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	S.TRAN_DATE BETWEEN '2005-04-01' 
	AND	'2005-06-30'
GROUP	BY L.LOCATION_NAME
)M(NAME,REV)
WHERE	K.NAME = M.NAME