SELECT	"_twm_bin1"	,"_twm_bin2"	,"_twm_bin3"	,"_twm_bin4"	,MIN("MKB_ITEM_QTY") AS "_twm_beg1"	,MIN("MKB_NUMBER_UNIQUE_ITEMS_QTY") AS "_twm_beg2"	,MIN("MKB_COST_AMT") AS "_twm_beg3"	,MIN("MKB_REV_AMT") AS "_twm_beg4"	,MAX("MKB_ITEM_QTY") AS "_twm_end1"	,MAX("MKB_NUMBER_UNIQUE_ITEMS_QTY") AS "_twm_end2"	,MAX("MKB_COST_AMT") AS "_twm_end3"	,MAX("MKB_REV_AMT") AS "_twm_end4"	,CAST(COUNT(*) AS FLOAT) AS "_twm_cnt"
FROM	(
SELECT	CASE 
	WHEN	"MKB_ITEM_QTY" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "MKB_ITEM_QTY" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "MKB_ITEM_QTY") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "MKB_ITEM_QTY" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin1"	,
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "MKB_NUMBER_UNIQUE_ITEMS_QTY") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "MKB_NUMBER_UNIQUE_ITEMS_QTY" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin2"	,
CASE	WHEN "MKB_COST_AMT" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "MKB_COST_AMT" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "MKB_COST_AMT") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "MKB_COST_AMT" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin3"	,
CASE	WHEN "MKB_REV_AMT" IS NULL THEN NULL 
ELSE	1 + (RANK() OVER (PARTITION BY 
CASE	WHEN "MKB_REV_AMT" IS NULL THEN NULL 
ELSE	0 
END	ORDER BY "MKB_REV_AMT") - 1) * 10 / COUNT(*) OVER (PARTITION BY 
CASE	WHEN "MKB_REV_AMT" IS NULL THEN NULL 
ELSE	0 
END	ROWS	BETWEEN UNBOUNDED PRECEDING 
	AND	UNBOUNDED FOLLOWING) 
END	AS "_twm_bin4"	,"MKB_ITEM_QTY"	,"MKB_NUMBER_UNIQUE_ITEMS_QTY"	,"MKB_COST_AMT"	,"MKB_REV_AMT"
FROM	"universal_schema"."SALES_TRANSACTION"
WHERE	TRAN_DATE < '2005-10-10'
) AS "T1"
GROUP	BY 1,2,3,4