SELECT	R.REGION_NAME "REGION NAME", EXTRACT(YEAR 
FROM	S.TRAN_DATE) "YEAR",
EXTRACT(MONTH 
FROM	S.TRAN_DATE) "MONTH" ,SUM(S.MKB_REV_AMT) "30 DAYS REVENUE"
FROM	
universal_schema.LOCATION L, universal_schema.ASSOCIATE A, universal_schema.SALES_TRANSACTION S,
		universal_schema.DISTRICT D, universal_schema.REGION R
WHERE	
S.TRAN_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
	AND	R.REGION_CD = 'REGION_A'
	AND	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	L.DISTRICT_CD = D.DISTRICT_CD
	AND	R.REGION_CD = D.REGION_CD
ORDER	BY "30 DAYS REVENUE" DESC
GROUP	BY R.REGION_NAME, "YEAR", "MONTH"