/*
 ZONENAME     : UNIVERSAL_SCHEMA.PRODUCT
 GENERATED BY : Quantum China Beijing R&D
 DATE         : Mon Mar  8 18:26:04 2010
 COPYRIGHT (C) 2010 BY TERADATA CORP.
*/
CREATE JOIN INDEX IPH_SJIX AS
    SELECT  IPH.LOCATION_ID                                  AS JIXC1,
            IPH.ITEM_ID                                      AS JIXC2,
            IPH.ITEM_PRICE_START_DT                          AS JIXC3,
            SUM(IPH.ITEM_PRICE_AMT)                          AS JIXC4
    FROM    ITEM_PRICE_HISTORY  AS IPH--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);


