SELECT	AD.ALL_DIVISIONS_NAME "ALL DIVISIONS NAME", SUM(S.MKB_REV_AMT) "ALL HISTORY REVENUE"
FROM	
universal_schema.LOCATION L, universal_schema.ASSOCIATE A, universal_schema.SALES_TRANSACTION S,
		universal_schema.DISTRICT D, universal_schema.REGION R, universal_schema.DIVISION DIV,
		universal_schema.ALL_DIVISIONS AD
WHERE	
S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	S.TRAN_DATE < '2005-07-01'
	AND	AD.ALL_DIVISIONS_CD = 'GLOBE_DIVISION_A'
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	L.DISTRICT_CD = D.DISTRICT_CD
	AND	R.REGION_CD = D.REGION_CD
	AND	R.DIVISION_CD = DIV.DIVISION_CD
	AND	DIV.ALL_DIVISIONS_CD = AD.ALL_DIVISIONS_CD
ORDER	BY "ALL HISTORY REVENUE" DESC
GROUP	BY AD.ALL_DIVISIONS_NAME