SELECT	D.DISTRICT_NAME,	I.ITEM_NAME,	SUM(STL.UNIT_SELLING_PRICE_AMT) REV,
			SUM(STL.UNIT_COST_AMT) COST,	CAST(REV-COST AS DEC(18,2)) AS MARGIN,
			MARGIN/REV * 100 AS PER_MARGIN	FROM	universal_schema.SALES_TRANSACTION_LINE STL,
			universal_schema.DISTRICT D,	universal_schema.LOCATION LOC,
			universal_schema.ITEM I	WHERE STL.ITEM_ID IN	(
SELECT	ITEM_ID 
FROM	universal_schema.ITEM 
WHERE	ITEM_NAME LIKE 'Good') 
	AND	STL.TRAN_LINE_DATE > '2005-06-26' 
	AND	STL.LOCATION=LOC.LOCATION_ID 
	AND	LOC.DISTRICT_CD = D.DISTRICT_CD 
	AND	STL.ITEM_ID = I.ITEM_ID	GROUP BY 1,2	ORDER BY 1,6 DESC