SELECT	M.NAME "PRODUCT NAME",M.REVENVE "REVENVE",M.COST "COST",
		M.MARGIN "MARGIN",(M.AMT * 100 (DECIMAL(18,2)))/ N.TOTAL (DECIMAL(18,
		2))"%"
FROM	
(
SELECT	TOP 10 I.ITEM_NAME, SUM(S.UNIT_SELLING_PRICE_AMT * S.ITEM_QTY),
SUM(S.UNIT_COST_AMT * S.ITEM_QTY),SUM(S.UNIT_SELLING_PRICE_AMT * S.ITEM_QTY) - SUM(S.UNIT_COST_AMT * S.ITEM_QTY) "MARGIN",
		COUNT(DISTINCT S.SALES_TRAN_ID)
FROM	universal_schema.ITEM I,universal_schema.SALES_TRANSACTION_LINE S
WHERE	S.TRAN_LINE_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
	AND	S.ITEM_ID = I.ITEM_ID
ORDER	BY "MARGIN" DESC
GROUP	BY I.ITEM_NAME
)M(NAME,REVENVE,COST,MARGIN,AMT),
(
SELECT	COUNT(DISTINCT SALES_TRAN_ID) 
FROM	universal_schema.SALES_TRANSACTION_LINE 
WHERE	TRAN_LINE_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30')N(TOTAL)