SELECT	L.LOCATION_NAME "STORE NAME", EXTRACT(YEAR 
FROM	S.TRAN_DATE) "YEAR",
EXTRACT(MONTH 
FROM	S.TRAN_DATE) "MONTH" ,SUM(S.MKB_REV_AMT) "30 DAYS REVENUE"
FROM	
universal_schema.LOCATION L, universal_schema.ASSOCIATE A, universal_schema.SALES_TRANSACTION S
WHERE	
S.TRAN_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
	AND	L.LOCATION_ID = 200
	AND	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
ORDER	BY "30 DAYS REVENUE" DESC
GROUP	BY L.LOCATION_NAME, "YEAR", "MONTH"