SELECT	A.INCOME_LEVEL "INCOME LEVEL", SUM(B.REFUNDED) "REFUNDED"
FROM	
(
SELECT	
CASE	WHEN INCOMEPERHOUSEHOLD >= 70000 THEN '70K+'
	WHEN	INCOMEPERHOUSEHOLD >= 60000 
	AND	INCOMEPERHOUSEHOLD < 70000 THEN '60K - 70K'
	WHEN	INCOMEPERHOUSEHOLD >= 50000 
	AND	INCOMEPERHOUSEHOLD < 60000 THEN '50K - 60K'
	WHEN	INCOMEPERHOUSEHOLD >= 40000 
	AND	INCOMEPERHOUSEHOLD < 50000 THEN '40K - 50K'
	WHEN	INCOMEPERHOUSEHOLD >= 30000 
	AND	INCOMEPERHOUSEHOLD < 40000 THEN '30K - 40K'
	WHEN	INCOMEPERHOUSEHOLD >= 20000 
	AND	INCOMEPERHOUSEHOLD < 30000 THEN '20K - 30K'
	WHEN	INCOMEPERHOUSEHOLD >= 10000 
	AND	INCOMEPERHOUSEHOLD < 20000 THEN '10K - 20K'
	WHEN	INCOMEPERHOUSEHOLD >= 0 
	AND	INCOMEPERHOUSEHOLD <10000 THEN '0K - 10K'
END	AS INCOME_LEVEL,
ZIPCODE
FROM	universal_schema.DEMOGRAPHICS)A(INCOME_LEVEL,ZIPCODE),
(
SELECT	
P.PARTY_ZIP,SUM(R.Return_Item_Qty * R.Unit_Refund_Amt)
FROM	universal_schema.PARTY P, universal_schema.RETURN_TRANSACTION_LINE R,
		universal_schema.SALES_TRANSACTION S
WHERE	
R.ORIGINAL_SALES_TRAN_ID = S.SALES_TRAN_ID
	AND	S.REWARD_CD = P.PARTY_ID
GROUP	BY P.PARTY_ZIP
)B(ZIPCODE,REFUNDED)
WHERE	
A.ZIPCODE = B.ZIPCODE
ORDER	BY SUM(B.REFUNDED) DESC
GROUP	BY A.INCOME_LEVEL