SELECT	
CASE	WHEN A.REV >=4000 THEN 'PREMIER'
	WHEN	A.REV >=3000 
	AND	rev <4000 THEN 'GOLD'
	WHEN	A.REV >=2000 
	AND	rev < 3000 THEN 'SILVER'
	WHEN	A.REV >= 0 
	AND	rev < 2000 THEN 'BRONZE'
END	AS Club_Level,
SUM(B.REFUNDED) "REFUNDED"
FROM	
(
SELECT	S.REWARD_CD,SUM(S.MKB_Rev_Amt)(FLOAT, NAMED rev)
FROM	universal_schema.SALES_TRANSACTION S
WHERE	S.REWARD_CD <> ''
	AND	S.REWARD_CD <> '0'
	AND	CAST(S.TRAN_DATE AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
GROUP	BY S.REWARD_CD
)A(REWARD_CD,REV),
(
SELECT	S.REWARD_CD,SUM(R.Return_Item_Qty * R.Unit_Refund_Amt)
FROM	universal_schema.SALES_TRANSACTION S, universal_schema.RETURN_TRANSACTION_LINE R
WHERE	S.SALES_TRAN_ID = R.ORIGINAL_SALES_TRAN_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
GROUP	BY S.REWARD_CD
)B(REWARD_CD,REFUNDED)
WHERE	
A.REWARD_CD = B.REWARD_CD
GROUP	BY CLUB_LEVEL