SELECT	AD.ALL_DIVISIONS_NAME "ALL DIVISIONS NAME", '2004-07 TO 2005-06' "PERIOD" ,
		SUM(S.MKB_REV_AMT) "LAST YEAR REVENUE"
FROM	
universal_schema.LOCATION L, universal_schema.ASSOCIATE A, universal_schema.SALES_TRANSACTION S,
		universal_schema.DISTRICT D, universal_schema.REGION R, universal_schema.DIVISION DIV,
		universal_schema.ALL_DIVISIONS AD
WHERE	
S.TRAN_DATE BETWEEN '2004-07-01' 
	AND	'2005-06-30'
	AND	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	L.DISTRICT_CD = D.DISTRICT_CD
	AND	R.REGION_CD = D.REGION_CD
	AND	R.DIVISION_CD = DIV.DIVISION_CD
	AND	DIV.ALL_DIVISIONS_CD = AD.ALL_DIVISIONS_CD
ORDER	BY "LAST YEAR REVENUE" DESC
GROUP	BY AD.ALL_DIVISIONS_NAME, "PERIOD"