SELECT	TOP 100 A.NAME "PRODUCT NAME", B.QTY * 100 / (A.QTY / 18) "%",
		RANK() OVER (
ORDER	BY "%" DESC) "RANK"
FROM	
(
SELECT	I.ITEM_NAME "PRODUCT NAME", SUM(R.RETURN_ITEM_QTY) "QTY"
FROM	universal_schema.ITEM I, universal_schema.RETURN_TRANSACTION_LINE R
WHERE	
R.RETURNED_ITEM_ID = I.ITEM_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
GROUP	BY "PRODUCT NAME")A(NAME,QTY),
(
SELECT	I.ITEM_NAME "PRODUCT NAME", SUM(R.RETURN_ITEM_QTY) "QTY"
FROM	universal_schema.ITEM I, universal_schema.RETURN_TRANSACTION_LINE R
WHERE	
R.RETURNED_ITEM_ID = I.ITEM_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2005-06-01'
GROUP	BY "PRODUCT NAME")B(NAME,QTY)
WHERE	
A.NAME = B.NAME
ORDER	BY "%" DESC