SELECT	TOP 3 I.ITEM_NAME "NAME", CAST( (CAST (S.SALES_TRAN_LINE_START_DTTM AS FORMAT 'HH'))AS CHAR(2) ) "HOUR",
		SUM(ITEM_QTY) / 30 "QTY"
FROM	universal_schema.SALES_TRANSACTION_LINE S, universal_schema.ITEM I
WHERE	
TRAN_LINE_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
	AND	S.ITEM_ID = 4300097940
	AND	S.ITEM_ID = I.ITEM_ID
ORDER	BY "QTY" DESC
GROUP	BY "NAME", "HOUR" 