SELECT	N.ITEM_NAME "MAIN PRODUCT", M.ITEM_NAME"DEPENDENT PRODUCT",
		(M.AMT * 100 (DECIMAL(18,2))) / N.AMT (DECIMAL(18,2)) "%"
FROM	
(
SELECT	TOP 5 I1.ITEM_NAME,COUNT(DISTINCT S0.SALES_TRAN_ID) "AMT" 
FROM	universal_schema.SALES_TRANSACTION_LINE S0, universal_schema.ITEM I1 
WHERE	SALES_TRAN_ID
IN (
SELECT	DISTINCT SALES_TRAN_ID 
FROM	universal_schema.SALES_TRANSACTION_LINE 
WHERE	ITEM_ID = 4300097940
	AND	TRAN_LINE_DATE BETWEEN '2005-04-01' 
	AND	'2005-06-30')
	AND	S0.ITEM_ID = I1.ITEM_ID
	AND	S0.ITEM_ID <> 4300097940
ORDER	BY AMT DESC
GROUP	BY I1.ITEM_NAME
)M(ITEM_NAME,AMT),
(
SELECT	I.ITEM_NAME,COUNT(DISTINCT S.SALES_TRAN_ID) 
FROM	universal_schema.SALES_TRANSACTION_LINE S,universal_schema.ITEM I 
WHERE	
S.ITEM_ID = 4300097940
	AND	S.TRAN_LINE_DATE BETWEEN '2005-04-01' 
	AND	'2005-06-30'
	AND	S.ITEM_ID = I.ITEM_ID
GROUP	BY I.ITEM_NAME
)N(ITEM_NAME,AMT)
ORDER	BY "%" DESC
GROUP	BY N.ITEM_NAME,M.ITEM_NAME,(M.AMT * 100 (DECIMAL(18,2))) / N.AMT (DECIMAL(18,
		2)) 