SELECT	TOP 100 I.ITEM_NAME "PRODUCT NAME", SUM(R.RETURN_ITEM_QTY) "QTY",
		RANK() OVER (
ORDER	BY "QTY" DESC) "RANK"
FROM	universal_schema.ITEM I, universal_schema.RETURN_TRANSACTION_LINE R
WHERE	
R.RETURNED_ITEM_ID = I.ITEM_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
ORDER	BY "QTY" DESC
GROUP	BY "PRODUCT NAME"