SELECT	
LOC.LOCATION_NAME,
I.ITEM_NAME,
N1.REV,
N1.COST,
N1.MARGIN,
N1.PER_MARGIN,
RANK() OVER (
ORDER	BY PER_MARGIN DESC) AS MARGIN_RANK
FROM	
(
SELECT	
STL.LOCATION,
STL.ITEM_ID,
SUM(STL.UNIT_SELLING_PRICE_AMT) REV,
SUM(STL.UNIT_COST_AMT) COST,
CAST(REV-COST AS DEC(18,2)) AS MARGIN,
MARGIN/REV * 100 AS PER_MARGIN
FROM	
universal_schema.SALES_TRANSACTION_LINE STL
WHERE	ITEM_ID IN
(
SELECT	ITEM_ID 
FROM	
universal_schema.ITEM 
WHERE	ITEM_NAME LIKE 'Good') 
	AND	
STL.TRAN_LINE_DATE > '2005-06-26' 
	AND	
STL.LOCATION = 200
GROUP	BY 1,2
)
N1(LOCATION,ITEM_ID, REV, COST,MARGIN,PER_MARGIN),
universal_schema.ITEM I,
universal_schema.LOCATION LOC
WHERE	
N1.ITEM_ID=I.ITEM_ID 
	AND	
N1.LOCATION=LOC.LOCATION_ID