SELECT	CA.NAME "STORE NAME",(C.AMT * 100(DECIMAL(18,2))) / CA.AMT (DECIMAL(18,
		2))"%1", RANK() OVER (
ORDER	BY (C.AMT * 100(DECIMAL(18,2))) / CA.AMT (DECIMAL(18,2)) ASC) "RANK 1",
(P.AMT * 100(DECIMAL(18,2))) / PT.AMT (DECIMAL(18,2))"%", RANK() OVER (
ORDER	BY (P.AMT * 100(DECIMAL(18,2))) / PT.AMT (DECIMAL(18,2)) ASC) "RANK 2"
FROM	
(
SELECT	L.LOCATION_NAME, COUNT(SALES_TRAN_ID)
FROM	universal_schema.SALES_TRANSACTION S, universal_schema.LOCATION L,
		universal_schema.ASSOCIATE A
WHERE	
S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	S.REWARD_cd = ''
	AND	TRAN_DATE BETWEEN '2005-05-01' 
	AND	'2005-05-31'
GROUP	BY L.LOCATION_NAME
)P(NAME,AMT),
(
SELECT	L.LOCATION_NAME, COUNT(SALES_TRAN_ID)
FROM	universal_schema.SALES_TRANSACTION S, universal_schema.LOCATION L,
		universal_schema.ASSOCIATE A
WHERE	
S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	S.REWARD_cd = ''
	AND	TRAN_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
GROUP	BY L.LOCATION_NAME
)C(NAME,AMT),
(
SELECT	L.LOCATION_NAME, COUNT(SALES_TRAN_ID)
FROM	universal_schema.SALES_TRANSACTION S, universal_schema.LOCATION L,
		universal_schema.ASSOCIATE A
WHERE	
S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	TRAN_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
GROUP	BY L.LOCATION_NAME
)CA(NAME,AMT),
(
SELECT	L.LOCATION_NAME, COUNT(SALES_TRAN_ID)
FROM	universal_schema.SALES_TRANSACTION S, universal_schema.LOCATION L,
		universal_schema.ASSOCIATE A
WHERE	
S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	TRAN_DATE BETWEEN '2005-05-01' 
	AND	'2005-05-31'
GROUP	BY L.LOCATION_NAME
)PT(NAME,AMT)
WHERE	C.NAME = P.NAME
	AND	P.NAME = CA.NAME
	AND	CA.NAME = PT.NAME
ORDER	BY "%" ASC