SELECT	L.LOCATION_NAME "STORE NAME", COUNT(S.SALES_TRAN_ID) "TOTAL VISITS",
		COUNT(DISTINCT S.REWARD_CD) "TOTAL VISIT CUSTOMERS", ((COUNT(S.SALES_TRAN_ID) - COUNT(DISTINCT S.REWARD_CD)) * 100 (DECIMAL(18,
		2))) / COUNT(DISTINCT S.REWARD_CD)(DECIMAL(18,2)) "%"
FROM	
universal_schema.LOCATION L, universal_schema.SALES_TRANSACTION S,
		universal_schema.ASSOCIATE A
WHERE	
S.TRAN_DATE BETWEEN '2005-06-01' 
	AND	'2005-06-30'
	AND	S.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID
	AND	A.LOCATION_ID = L.LOCATION_ID
	AND	SUBSTR(TRIM(S.REWARD_CD),1,3) = L.LOCATION_ID
ORDER	BY "%" DESC
GROUP	BY L.LOCATION_NAME