/*
 ZONENAME     : UNIVERSAL_SCHEMA.CUSTOMER
 GENERATED BY : Quantum China Beijing R&D
 DATE         : Mon Mar  8 18:26:04 2010
 COPYRIGHT (C) 2010 BY TERADATA CORP.
*/
/*USI Construction. */
CREATE UNIQUE INDEX (
            PARTY_ID
     )
ON UNIVERSAL_SCHEMA.PARTY; 

/*


RI Construction!*/

