/*
 ZONENAME     : UNIVERSAL_SCHEMA.ORDER
 GENERATED BY : Quantum China Beijing R&D
 DATE         : Mon Mar  8 18:26:04 2010
 COPYRIGHT (C) 2010 BY TERADATA CORP.
*/
CREATE JOIN INDEX STL_I_MLJIX AS
    SELECT  I.ITEM_ID                           AS JIXC1,
            I.ITEM_NAME                         AS JIXC2,
            STL.TRAN_LINE_DATE                  AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6,
            STL.SALES_TRAN_ID                   AS JIXC7
    FROM    SALES_TRANSACTION_LINE   AS STL,
            ITEM                     AS I--@END
    WHERE STL.ITEM_ID = I.ITEM_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX STL_SJIX AS
    SELECT  STL.LOCATION                        AS JIXC1,
            STL.ITEM_ID                         AS JIXC2,
            STL.TRAN_LINE_DATE                  AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6
    FROM    SALES_TRANSACTION_LINE   AS STL--@END
    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX RTL_I_MLJIX AS
    SELECT  I.ITEM_ID                           AS JIXC1,
            I.ITEM_NAME                         AS JIXC2,
            RETURN_TRAN_LINE_START_DTTM         AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    RETURN_TRANSACTION_LINE   AS RTL,
            ITEM                      AS I--@END
    WHERE RTL.RETURNED_ITEM_ID = I.ITEM_ID
--    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX RTL_SJIX AS
    SELECT  RTL.LOCATION_ID                       AS JIXC1,
            RTL.RETURNED_ITEM_ID                  AS JIXC2,
            RETURN_TRAN_LINE_START_DTTM           AS JIXC3,
            RTL.RETURN_ITEM_QTY                   AS JIXC4,
            RTL.UNIT_REFUND_AMT                   AS JIXC5
    FROM    RETURN_TRANSACTION_LINE   AS RTL--@END
--    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX STL_ST_P_MLJIX AS
    SELECT  P.PARTY_ID                          AS JIXC1,
            STL.ITEM_ID                         AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6
    FROM    SALES_TRANSACTION_LINE   AS STL,
            SALES_TRANSACTION        AS ST,
            PARTY                    AS P--@END
    WHERE   ST.SALES_TRAN_ID = STL.SALES_TRAN_ID  AND
            ST.REWARD_CD = P.PARTY_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX STL_ST_MLJIX AS
    SELECT  STL.ITEM_ID                         AS JIXC1,
            ST.REWARD_CD                        AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6
    FROM    SALES_TRANSACTION_LINE   AS STL,
            SALES_TRANSACTION        AS ST--@END
    WHERE   ST.SALES_TRAN_ID = STL.SALES_TRAN_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX RTL_ST_P_MLJIX AS
    SELECT  P.PARTY_ID                          AS JIXC1,
            RTL.RETURNED_ITEM_ID                AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    RETURN_TRANSACTION_LINE   AS RTL,
            SALES_TRANSACTION         AS ST,
            PARTY                     AS P--@END
    WHERE   ST.SALES_TRAN_ID = RTL.ORIGINAL_SALES_TRAN_ID  AND
            ST.REWARD_CD = P.PARTY_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX RTL_ST_MLJIX AS
    SELECT  RTL.RETURNED_ITEM_ID                AS JIXC1,
            ST.REWARD_CD                        AS JIXC2,
            RTL.RETURN_TRAN_LINE_START_DTTM     AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    RETURN_TRANSACTION_LINE   AS RTL,
            SALES_TRANSACTION         AS ST--@END
    WHERE   ST.SALES_TRAN_ID = RTL.ORIGINAL_SALES_TRAN_ID
--    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX ST_P_MLJIX AS
    SELECT  ST.SALES_TRAN_ID                    AS JIXC1,
            P.PARTY_ID                          AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            ST.MKB_COST_AMT                     AS JIXC4,
            ST.MKB_ITEM_QTY                     AS JIXC5,
            ST.MKB_NUMBER_UNIQUE_ITEMS_QTY      AS JIXC6,
            ST.MKB_REV_AMT                      AS JIXC7
    FROM    SALES_TRANSACTION         AS ST,
            PARTY                     AS P--@END
    WHERE   ST.REWARD_CD = P.PARTY_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX ST_SJIX AS
    SELECT  ST.REWARD_CD                        AS JIXC1,
            ST.ASSOCIATE_PARTY_ID               AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            SUM(ST.MKB_COST_AMT)                AS JIXC4,
            SUM(ST.MKB_ITEM_QTY)                AS JIXC5,
            SUM(ST.MKB_NUMBER_UNIQUE_ITEMS_QTY) AS JIXC6,
            SUM(ST.MKB_REV_AMT)                 AS JIXC7
    FROM   SALES_TRANSACTION         AS ST--@END
    GROUP BY JIXC1, JIXC2, JIXC3
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX P_D_MLJIX AS
    SELECT  P.PARTY_ZIP                     AS JIXC1,
            D.INCOMEPERHOUSEHOLD            AS JIXC2
    FROM    PARTY               AS P,
            DEMOGRAPHICS        AS D--@END    
    WHERE   P.PARTY_ZIP = D.ZIPCODE
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX IPH_SJIX AS
    SELECT  IPH.LOCATION_ID                                  AS JIXC1,
            IPH.ITEM_ID                                      AS JIXC2,
            IPH.ITEM_PRICE_START_DT                          AS JIXC3,
            SUM(IPH.ITEM_PRICE_AMT)                          AS JIXC4
    FROM    ITEM_PRICE_HISTORY  AS IPH--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);


