/*
 ZONENAME     : UNIVERSAL_SCHEMA.OTHERS
 GENERATED BY : Quantum China Beijing R&D
 DATE         : Mon Mar  8 18:26:04 2010
 COPYRIGHT (C) 2010 BY TERADATA CORP.
*/
CREATE JOIN INDEX L_D_R_DIV_AD_MLJIX AS
    SELECT  AD.ALL_DIVISIONS_NAME             AS JIXC1,
            D.DISTRICT_NAME                   AS JIXC2,
            R.REGION_NAME                     AS JIXC3,
            DIV.DIVISION_NAME                 AS JIXC4,
            L.LOCATION_NAME                   AS JIXC5
    FROM    LOCATION               AS L,
            DISTRICT               AS D,
            REGION                 AS R,
            DIVISION               AS DIV,
            ALL_DIVISIONS          AS AD--@END
    WHERE   L.DISTRICT_CD = D.DISTRICT_CD   AND
            R.REGION_CD = D.REGION_CD       AND
            R.DIVISION_CD = DIV.DIVISION_CD AND
            DIV.ALL_DIVISIONS_CD = AD.ALL_DIVISIONS_CD
PRIMARY INDEX(JIXC5);

CREATE JOIN INDEX IIP_SJIX AS
    SELECT  IIP.LOCATION_ID                                   AS JIXC1,
            IIP.ITEM_ID                                       AS JIXC2,
            IIP.ITEM_INVENTORY_PLAN_DT                        AS JIXC3,
            SUM(IIP.PLAN_ON_HAND_QTY)                         AS JIXC4,
            SUM(IIP.PLAN_ON_HAND_RETAIL_AMT)                  AS JIXC5
    FROM    ITEM_INVENTORY_PLAN  AS IIP--@END
    WHERE   ITEM_INVENTORY_PLAN_DT > '2000-04-25'
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX ABE_SJIX AS
    SELECT  ABE.ASSOCIATE_PARTY_ID                     AS JIXC1,
            ABE.ASSOCIATE_EXPNS_TYPE_CD                AS JIXC2,
            ABE.PERIOD_END_DT                          AS JIXC3,
            SUM(ABE.BENEFIT_HOURS_QTY)                 AS JIXC4,
            SUM(ABE.BENEFIT_COST_AMT)                  AS JIXC5
    FROM    ASSOCIATE_BENEFIT_EXPENSE  AS ABE--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC3);

CREATE JOIN INDEX ALE_SJIX AS
    SELECT  ALE.ASSOCIATE_PARTY_ID                     AS JIXC1,
            ALE.ASSOCIATE_EXPNS_TYPE_CD                AS JIXC2,
            ALE.PERIOD_END_DT                          AS JIXC3,
            SUM(ALE.LABOR_HOURS_QTY)                   AS JIXC4,
            SUM(ALE.LABOR_COST_AMT)                    AS JIXC5
    FROM    ASSOCIATE_LABOR_EXPENSE  AS ALE--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);


