SELECT	TOP 10 A.NAME "PRODUCT NAME", A.REFUNDED "AVE OF 18 MONTHS",
		B.REFUNDED "30 DAYS", (B.REFUNDED * 100 (DECIMAL(18,2)))/ A.REFUNDED (DECIMAL(18,
		2)) "%"
FROM	
(
SELECT	I.ITEM_NAME "PRODUCT NAME", SUM(R.Return_Item_Qty * R.Unit_Refund_Amt)/18 "# OF REFUNDED"
FROM	universal_schema.ITEM I, universal_schema.RETURN_TRANSACTION_LINE R
WHERE	I.ITEM_ID = R.RETURNED_ITEM_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
GROUP	BY "PRODUCT NAME")A(NAME,REFUNDED),
(
SELECT	I.ITEM_NAME "PRODUCT NAME", SUM(R.Return_Item_Qty * R.Unit_Refund_Amt) "# OF REFUNDED"
FROM	universal_schema.ITEM I, universal_schema.RETURN_TRANSACTION_LINE R
WHERE	I.ITEM_ID = R.RETURNED_ITEM_ID
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2005-06-01'
GROUP	BY "PRODUCT NAME")B(NAME,REFUNDED)
WHERE	A.NAME = B.NAME
ORDER	BY "30 DAYS" DESC