SELECT	
    I.ITEM_NAME,
    LOC.LOCATION_NAME,
    N1.Y_SUM_QTY AS Y_SUM_QTY,
    N1.Y_SUM_PRICE AS Y_SUM_REV,
    CAST(SUM(STL.ITEM_QTY) AS DEC(18,2)) AS LW_SUM_QTY,
    CAST(SUM(STL.UNIT_SELLING_PRICE_AMT) AS DEC(18,2)) AS LW_SUM_REV
--    , CAST ((Y_SUM_QTY / LW_SUM_QTY) * 100 AS DEC(18,2)) AS QTY_PER
--    , CAST ((Y_SUM_REV / LW_SUM_REV) * 100 AS DEC(18,2)) AS REV_PER
FROM	
(
    SELECT	
        STL.ITEM_ID,
        STL.LOCATION,
        SUM(STL.ITEM_QTY) Y_SUM_QTY,
        SUM(STL.UNIT_SELLING_PRICE_AMT) Y_SUM_PRICE
    FROM	
    universal_schema.SALES_TRANSACTION_LINE STL
    WHERE	
        STL.TRAN_LINE_DATE = DATE '2005-06-30'
        AND	
        STL.LOCATION = 200
        AND	
        STL.ITEM_ID IN 
        (
            SELECT	ITEM_ID 
            FROM	
            universal_schema.ITEM 
            WHERE	
            ITEM_NAME LIKE 'Good'
        )
    GROUP	BY 1,2
) N1(ITEM_ID, LOCATION, Y_SUM_QTY,Y_SUM_PRICE)
, universal_schema.SALES_TRANSACTION_LINE STL
, universal_schema.ITEM I
, universal_schema.LOCATION LOC
WHERE	
    N1.ITEM_ID=STL.ITEM_ID 
	AND	
    N1.LOCATION=STL.LOCATION 
	AND	
    STL.TRAN_LINE_DATE = DATE '2005-06-30' - INTERVAL '7' DAY 
	AND	
    STL.ITEM_ID = I.ITEM_ID 
	AND	
    STL.LOCATION = LOC.LOCATION_ID
GROUP	BY 1,2,3,4
