SELECT	
I.ITEM_NAME,
SUM(STL.UNIT_SELLING_PRICE_AMT)/90 AS PREV,
SUM(STL.UNIT_COST_AMT)/90 AS COST,
PREV-COST AS MARGIN
FROM	
universal_schema.ITEM I,
universal_schema.SALES_TRANSACTION_LINE STL
WHERE	STL.TRAN_LINE_DATE < DATE'2005-06-30'
	AND	
STL.TRAN_LINE_DATE >= DATE'2005-04-01'
	AND	
STL.ITEM_ID = I.ITEM_ID
GROUP	BY 1