/*
 ZONENAME     : UNIVERSAL_SCHEMA.ADW44
 GENERATED BY : Quantum China Beijing R&D
 DATE         : Mon Mar  8 18:26:04 2010
 COPYRIGHT (C) 2010 BY TERADATA CORP.
*/
CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji01 AS
    SELECT  L.LOCATION_ID                       AS JIXC1,
            I.ITEM_ID                           AS JIXC2,
            L.LOCATION_NAME                     AS JIXC3,
            I.ITEM_NAME                         AS JIXC4,
            STL.TRAN_LINE_DATE                  AS JIXC5,
            STL.ITEM_QTY                        AS JIXC6,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC7,
            STL.UNIT_COST_AMT                   AS JIXC8
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION_LINE   AS STL,
            UNIVERSAL_SCHEMA.ITEM                     AS I,
            UNIVERSAL_SCHEMA.LOCATION                 AS L--@END
    WHERE STL.ITEM_ID = I.ITEM_ID    AND
          STL.LOCATION = L.LOCATION_ID
    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji02 AS
    SELECT  I.ITEM_ID                           AS JIXC1,
            I.ITEM_NAME                         AS JIXC2,
            STL.TRAN_LINE_DATE                  AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6,
            STL.SALES_TRAN_ID                   AS JIXC7
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION_LINE   AS STL,
            UNIVERSAL_SCHEMA.ITEM                     AS I--@END
    WHERE STL.ITEM_ID = I.ITEM_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji03 AS
    SELECT  L.LOCATION_ID                       AS JIXC1,
            L.LOCATION_NAME                     AS JIXC2,
            STL.TRAN_LINE_DATE                  AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6,
            STL.SALES_TRAN_ID                   AS JIXC7
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION_LINE   AS STL,
            UNIVERSAL_SCHEMA.LOCATION                 AS L--@END
    WHERE   STL.LOCATION = L.LOCATION_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji04 AS
    SELECT  STL.LOCATION                        AS JIXC1,
            STL.ITEM_ID                         AS JIXC2,
            STL.TRAN_LINE_DATE                  AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION_LINE   AS STL--@END
    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji05 AS
    SELECT  L.LOCATION_ID                       AS JIXC1,
            I.ITEM_ID                           AS JIXC2,
            L.LOCATION_NAME                     AS JIXC3,
            I.ITEM_NAME                         AS JIXC4,
            RETURN_TRAN_LINE_START_DTTM         AS JIXC5,
            RTL.RETURN_ITEM_QTY                 AS JIXC6,
            RTL.UNIT_REFUND_AMT                 AS JIXC7
    FROM    UNIVERSAL_SCHEMA.RETURN_TRANSACTION_LINE   AS RTL,
            UNIVERSAL_SCHEMA.ITEM                      AS I,
            UNIVERSAL_SCHEMA.LOCATION                  AS L--@END
    WHERE RTL.RETURNED_ITEM_ID = I.ITEM_ID    AND
          RTL.LOCATION_ID = L.LOCATION_ID
--    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji06 AS
    SELECT  I.ITEM_ID                           AS JIXC1,
            I.ITEM_NAME                         AS JIXC2,
            RETURN_TRAN_LINE_START_DTTM         AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    UNIVERSAL_SCHEMA.RETURN_TRANSACTION_LINE   AS RTL,
            UNIVERSAL_SCHEMA.ITEM                      AS I--@END
    WHERE RTL.RETURNED_ITEM_ID = I.ITEM_ID
--    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji07 AS
    SELECT  L.LOCATION_ID                       AS JIXC1,
            L.LOCATION_NAME                     AS JIXC2,
            RETURN_TRAN_LINE_START_DTTM         AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    UNIVERSAL_SCHEMA.RETURN_TRANSACTION_LINE   AS RTL,
            UNIVERSAL_SCHEMA.LOCATION                  AS L
    WHERE   RTL.LOCATION_ID = L.LOCATION_ID--@END
--    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji08 AS
    SELECT  RTL.LOCATION_ID                       AS JIXC1,
            RTL.RETURNED_ITEM_ID                  AS JIXC2,
            RETURN_TRAN_LINE_START_DTTM           AS JIXC3,
            RTL.RETURN_ITEM_QTY                   AS JIXC4,
            RTL.UNIT_REFUND_AMT                   AS JIXC5
    FROM    UNIVERSAL_SCHEMA.RETURN_TRANSACTION_LINE   AS RTL--@END
--    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji09 AS
    SELECT  P.PARTY_ID                          AS JIXC1,
            STL.ITEM_ID                         AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION_LINE   AS STL,
            UNIVERSAL_SCHEMA.SALES_TRANSACTION        AS ST,
            UNIVERSAL_SCHEMA.PARTY                    AS P--@END
    WHERE   ST.SALES_TRAN_ID = STL.SALES_TRAN_ID  AND
            ST.REWARD_CD = P.PARTY_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji10 AS
    SELECT  STL.ITEM_ID                         AS JIXC1,
            ST.REWARD_CD                        AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            STL.ITEM_QTY                        AS JIXC4,
            STL.UNIT_SELLING_PRICE_AMT          AS JIXC5,
            STL.UNIT_COST_AMT                   AS JIXC6
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION_LINE   AS STL,
            UNIVERSAL_SCHEMA.SALES_TRANSACTION        AS ST--@END
    WHERE   ST.SALES_TRAN_ID = STL.SALES_TRAN_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji11 AS
    SELECT  P.PARTY_ID                          AS JIXC1,
            RTL.RETURNED_ITEM_ID                AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    UNIVERSAL_SCHEMA.RETURN_TRANSACTION_LINE   AS RTL,
            UNIVERSAL_SCHEMA.SALES_TRANSACTION         AS ST,
            UNIVERSAL_SCHEMA.PARTY                     AS P--@END
    WHERE   ST.SALES_TRAN_ID = RTL.ORIGINAL_SALES_TRAN_ID  AND
            ST.REWARD_CD = P.PARTY_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji12 AS
    SELECT  RTL.RETURNED_ITEM_ID                AS JIXC1,
            ST.REWARD_CD                        AS JIXC2,
            RTL.RETURN_TRAN_LINE_START_DTTM     AS JIXC3,
            RTL.RETURN_ITEM_QTY                 AS JIXC4,
            RTL.UNIT_REFUND_AMT                 AS JIXC5
    FROM    UNIVERSAL_SCHEMA.RETURN_TRANSACTION_LINE   AS RTL,
            UNIVERSAL_SCHEMA.SALES_TRANSACTION         AS ST--@END
    WHERE   ST.SALES_TRAN_ID = RTL.ORIGINAL_SALES_TRAN_ID
--    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji13 AS
    SELECT  ST.SALES_TRAN_ID                    AS JIXC1,
            P.PARTY_ID                          AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            ST.MKB_COST_AMT                     AS JIXC4,
            ST.MKB_ITEM_QTY                     AS JIXC5,
            ST.MKB_NUMBER_UNIQUE_ITEMS_QTY      AS JIXC6,
            ST.MKB_REV_AMT                      AS JIXC7
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION         AS ST,
            UNIVERSAL_SCHEMA.PARTY                     AS P--@END
    WHERE   ST.REWARD_CD = P.PARTY_ID
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji14 AS
    SELECT  ST.REWARD_CD                        AS JIXC1,
            ST.ASSOCIATE_PARTY_ID               AS JIXC2,
            ST.TRAN_DATE                        AS JIXC3,
            SUM(ST.MKB_COST_AMT)                AS JIXC4,
            SUM(ST.MKB_ITEM_QTY)                AS JIXC5,
            SUM(ST.MKB_NUMBER_UNIQUE_ITEMS_QTY) AS JIXC6,
            SUM(ST.MKB_REV_AMT)                 AS JIXC7
    FROM   UNIVERSAL_SCHEMA.SALES_TRANSACTION         AS ST--@END
    GROUP BY JIXC1, JIXC2, JIXC3
    ORDER BY JIXC3
PRIMARY INDEX(JIXC1,JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji15 AS
    SELECT  L.LOCATION_ID                               AS JIXC1,
            L.LOCATION_NAME                             AS JIXC2,
            A.ASSOCIATE_PARTY_ID                        AS JIXC3,
            ST.TRAN_DATE                                AS JIXC4,
            ST.MKB_COST_AMT                             AS JIXC5,
            ST.MKB_ITEM_QTY                             AS JIXC6,
            ST.MKB_NUMBER_UNIQUE_ITEMS_QTY              AS JIXC7,
            ST.MKB_REV_AMT                              AS JIXC8
    FROM    UNIVERSAL_SCHEMA.SALES_TRANSACTION         AS ST,
            UNIVERSAL_SCHEMA.ASSOCIATE                 AS A,
            UNIVERSAL_SCHEMA.LOCATION                  AS L--@END
    WHERE   ST.ASSOCIATE_PARTY_ID = A.ASSOCIATE_PARTY_ID  AND
            A.LOCATION_ID = L.LOCATION_ID
    ORDER BY JIXC4
PRIMARY INDEX(JIXC1, JIXC3);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji16 AS
    SELECT  P.PARTY_ZIP                     AS JIXC1,
            D.INCOMEPERHOUSEHOLD            AS JIXC2
    FROM    UNIVERSAL_SCHEMA.PARTY               AS P,
            UNIVERSAL_SCHEMA.DEMOGRAPHICS        AS D--@END    
    WHERE   P.PARTY_ZIP = D.ZIPCODE
PRIMARY INDEX(JIXC1);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji17 AS
    SELECT  AD.ALL_DIVISIONS_NAME             AS JIXC1,
            D.DISTRICT_NAME                   AS JIXC2,
            R.REGION_NAME                     AS JIXC3,
            DIV.DIVISION_NAME                 AS JIXC4,
            L.LOCATION_NAME                   AS JIXC5
    FROM    UNIVERSAL_SCHEMA.LOCATION               AS L,
            UNIVERSAL_SCHEMA.DISTRICT               AS D,
            UNIVERSAL_SCHEMA.REGION                 AS R,
            UNIVERSAL_SCHEMA.DIVISION               AS DIV,
            UNIVERSAL_SCHEMA.ALL_DIVISIONS          AS AD--@END
    WHERE   L.DISTRICT_CD = D.DISTRICT_CD   AND
            R.REGION_CD = D.REGION_CD       AND
            R.DIVISION_CD = DIV.DIVISION_CD AND
            DIV.ALL_DIVISIONS_CD = AD.ALL_DIVISIONS_CD
PRIMARY INDEX(JIXC5);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji18 AS
    SELECT  L.LOCATION_ID                         AS JIXC1,
            L.LOCATION_NAME                       AS JIXC2,
            I.ITEM_ID                             AS JIXC3,
            I.ITEM_NAME                           AS JIXC4,
            II.ITEM_INV_DT                        AS JIXC5,
            II.ON_HAND_UNIT_QTY                   AS JIXC6,
            II.ON_HAND_AT_RETAIL_AMT              AS JIXC7,
            II.ON_HAND_COST_AMT                   AS JIXC8,
            II.ON_ORDER_QTY                       AS JIXC9 
    FROM    UNIVERSAL_SCHEMA.ITEM_INVENTORY     AS II,
            UNIVERSAL_SCHEMA.ITEM               AS I,
            UNIVERSAL_SCHEMA.LOCATION           AS L--@END
    WHERE   II.ITEM_ID = I.ITEM_ID   AND
            II.LOCATION_ID = L.LOCATION_ID
    ORDER BY JIXC5
PRIMARY INDEX(JIXC1, JIXC3);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji19 AS
    SELECT  IIP.LOCATION_ID                                   AS JIXC1,
            IIP.ITEM_ID                                       AS JIXC2,
            IIP.ITEM_INVENTORY_PLAN_DT                        AS JIXC3,
            SUM(IIP.PLAN_ON_HAND_QTY)                         AS JIXC4,
            SUM(IIP.PLAN_ON_HAND_RETAIL_AMT)                  AS JIXC5
    FROM    UNIVERSAL_SCHEMA.ITEM_INVENTORY_PLAN  AS IIP--@END
    WHERE   IIP.ITEM_INVENTORY_PLAN_DT > '2000-04-25'
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji20 AS
    SELECT  IPH.LOCATION_ID                                  AS JIXC1,
            IPH.ITEM_ID                                      AS JIXC2,
            IPH.ITEM_PRICE_START_DT                          AS JIXC3,
            SUM(IPH.ITEM_PRICE_AMT)                          AS JIXC4
    FROM    UNIVERSAL_SCHEMA.ITEM_PRICE_HISTORY  AS IPH--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji21 AS
    SELECT  ABE.ASSOCIATE_PARTY_ID                     AS JIXC1,
            ABE.ASSOCIATE_EXPNS_TYPE_CD                AS JIXC2,
            ABE.PERIOD_END_DT                          AS JIXC3,
            SUM(ABE.BENEFIT_HOURS_QTY)                 AS JIXC4,
            SUM(ABE.BENEFIT_COST_AMT)                  AS JIXC5
    FROM    UNIVERSAL_SCHEMA.ASSOCIATE_BENEFIT_EXPENSE  AS ABE--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC3);

CREATE JOIN INDEX UNIVERSAL_SCHEMA.usji22 AS
    SELECT  ALE.ASSOCIATE_PARTY_ID                     AS JIXC1,
            ALE.ASSOCIATE_EXPNS_TYPE_CD                AS JIXC2,
            ALE.PERIOD_END_DT                          AS JIXC3,
            SUM(ALE.LABOR_HOURS_QTY)                   AS JIXC4,
            SUM(ALE.LABOR_COST_AMT)                    AS JIXC5
    FROM    UNIVERSAL_SCHEMA.ASSOCIATE_LABOR_EXPENSE  AS ALE--@END
    ORDER BY JIXC3
    GROUP BY 1,2,3
PRIMARY INDEX(JIXC1, JIXC2);


