SELECT	I.ITEM_NAME "PRODUCT NAME",
SUM(CAST(R.Return_Tran_Line_Start_Dttm AS DATE) - S.TRAN_LINE_DATE)/COUNT(S.SALES_TRAN_ID) "AVE DAYS FOR RETURN"
FROM	universal_schema.SALES_TRANSACTION_LINE S, universal_schema.RETURN_TRANSACTION_LINE R,
		universal_schema.ITEM I
WHERE	
R.ORIGINAL_SALES_TRAN_ID = S.SALES_TRAN_ID
	AND	R.ORIGINAL_SALES_TRAN_LINE_NUM= S.SALES_TRAN_LINE_NUM(char(4))
	AND	trim(R.RETURNED_ITEM_ID) = 4300097940
	AND	trim(R.RETURNED_ITEM_ID) = trim(S.ITEM_ID)
	AND	I.ITEM_ID = 4300097940
	AND	CAST(R.Return_Tran_Line_Start_Dttm AS DATE FORMAT 'YYYY-MM-DD') >= '2004-01-01'
GROUP	BY "PRODUCT NAME"