SELECT	"T1"."xbin_SALES_TRAN_ID"	,"T1"."xbeg_SALES_TRAN_ID"	,"T1"."xend_SALES_TRAN_ID"	,"T1"."xbin_TRAN_DATE"	,"T1"."xbeg_TRAN_DATE"	,"T1"."xend_TRAN_DATE"	,"T1"."xcnt"	,"T1"."xpct"	,"T2"."Associate_Party_Id" AS "ovly_Associate_Party_Id"	,CAST(COUNT(*) AS FLOAT) AS "xocnt"	,100.000 * "xocnt" / MAX("xcnt") AS "xobpct"	,100.000 * "xocnt" / MAX("T2"."xall") AS "xopct"	,MIN(CAST("MKB_ITEM_QTY" AS FLOAT)) AS "xmin_MKB_ITEM_QTY"	,MAX(CAST("MKB_ITEM_QTY" AS FLOAT)) AS "xmax_MKB_ITEM_QTY"	,AVG(CAST("MKB_ITEM_QTY" AS FLOAT)) AS "xmean_MKB_ITEM_QTY"	,STDDEV_POP(CAST("MKB_ITEM_QTY" AS FLOAT)) AS "xstd_MKB_ITEM_QTY"
FROM	
(
SELECT	CASE	WHEN "xnmax_SALES_TRAN_ID" = "xmin_SALES_TRAN_ID" THEN 1	WHEN "xnmax_SALES_TRAN_ID" = "SALES_TRAN_ID" THEN "xbins_SALES_TRAN_ID"	ELSE CAST(("SALES_TRAN_ID" - "xmin_SALES_TRAN_ID")/(CAST("xnmax_SALES_TRAN_ID" - "xmin_SALES_TRAN_ID" AS FLOAT)/"xbins_SALES_TRAN_ID") + 1 AS INTEGER) 
END	AS "xbin_SALES_TRAN_ID"	,"xmin_SALES_TRAN_ID" + ("xbin_SALES_TRAN_ID" - 1) * "xwid_SALES_TRAN_ID" AS "xbeg_SALES_TRAN_ID"	,
CASE	WHEN ("xbeg_SALES_TRAN_ID" + "xwid_SALES_TRAN_ID") > "xmax_SALES_TRAN_ID" THEN "xmax_SALES_TRAN_ID" 
ELSE	"xbeg_SALES_TRAN_ID" + "xwid_SALES_TRAN_ID" 
END	AS "xend_SALES_TRAN_ID"	,
CASE	WHEN "xnmax_TRAN_DATE" = "xmin_TRAN_DATE" THEN 1	WHEN "xnmax_TRAN_DATE" = "TRAN_DATE" THEN "xbins_TRAN_DATE"	ELSE CAST(("TRAN_DATE" - "xmin_TRAN_DATE")/(CAST("xnmax_TRAN_DATE" - "xmin_TRAN_DATE" AS FLOAT)/"xbins_TRAN_DATE") + 1 AS INTEGER) 
END	AS "xbin_TRAN_DATE"	,CAST("xmin_TRAN_DATE" + ("xbin_TRAN_DATE" - 1) * "xwid_TRAN_DATE" AS INT) + 19000000 AS "xbeg_TRAN_DATE"	,
CASE	WHEN ("xmin_TRAN_DATE" + ("xbin_TRAN_DATE" - 1) * "xwid_TRAN_DATE" + "xwid_TRAN_DATE") > "xmax_TRAN_DATE" THEN CAST("xmax_TRAN_DATE" AS INT) + 19000000 
ELSE	CAST(("xmin_TRAN_DATE" + ("xbin_TRAN_DATE" - 1) * "xwid_TRAN_DATE" + "xwid_TRAN_DATE") AS INT) + 19000000 
END	AS "xend_TRAN_DATE"	,CAST(COUNT(*) AS FLOAT) AS "xcnt"	,100.000 * "xcnt" / MAX("xall") AS "xpct"
FROM	"universal_schema"."SALES_TRANSACTION"
,(
SELECT	MIN("SALES_TRAN_ID") AS "xmin_SALES_TRAN_ID"	,MAX("SALES_TRAN_ID") AS "xmax_SALES_TRAN_ID"	,MIN(10) AS "xwid_SALES_TRAN_ID"	,CAST(("xmax_SALES_TRAN_ID" - "xmin_SALES_TRAN_ID") / "xwid_SALES_TRAN_ID" AS INTEGER) + (
CASE	("xmax_SALES_TRAN_ID" - "xmin_SALES_TRAN_ID") MOD "xwid_SALES_TRAN_ID" 
	WHEN	0 THEN 0 
ELSE	1 
END	) AS "xbins_SALES_TRAN_ID"	,"xmin_SALES_TRAN_ID" + "xbins_SALES_TRAN_ID"*"xwid_SALES_TRAN_ID" AS "xnmax_SALES_TRAN_ID"	,MIN("TRAN_DATE") AS "xmin_TRAN_DATE"	,MAX("TRAN_DATE") AS "xmax_TRAN_DATE"	,MIN(5) AS "xwid_TRAN_DATE"	,CAST(("xmax_TRAN_DATE" - "xmin_TRAN_DATE") / "xwid_TRAN_DATE" AS INTEGER) + (
CASE	("xmax_TRAN_DATE" - "xmin_TRAN_DATE") MOD "xwid_TRAN_DATE" 
	WHEN	0 THEN 0 
ELSE	1 
END	) AS "xbins_TRAN_DATE"	,"xmin_TRAN_DATE" + "xbins_TRAN_DATE"*"xwid_TRAN_DATE" AS "xnmax_TRAN_DATE"	,CAST(COUNT(*) AS FLOAT) AS "xall"
FROM	"universal_schema"."SALES_TRANSACTION"
) A
GROUP	BY 1,2,3,4,5,6
) T1,
(
SELECT	"xall"	,"Associate_Party_Id"	,"MKB_ITEM_QTY"	,"SALES_TRAN_ID"	,"TRAN_DATE"	,
CASE	WHEN "xnmax_SALES_TRAN_ID" = "xmin_SALES_TRAN_ID" THEN 1	WHEN "xnmax_SALES_TRAN_ID" = "SALES_TRAN_ID" THEN "xbins_SALES_TRAN_ID"	ELSE CAST(("SALES_TRAN_ID" - "xmin_SALES_TRAN_ID")/(CAST("xnmax_SALES_TRAN_ID" - "xmin_SALES_TRAN_ID" AS FLOAT)/"xbins_SALES_TRAN_ID") + 1 AS INTEGER) 
END	AS "xbin_SALES_TRAN_ID"	,
CASE	WHEN "xnmax_TRAN_DATE" = "xmin_TRAN_DATE" THEN 1	WHEN "xnmax_TRAN_DATE" = "TRAN_DATE" THEN "xbins_TRAN_DATE"	ELSE CAST(("TRAN_DATE" - "xmin_TRAN_DATE")/(CAST("xnmax_TRAN_DATE" - "xmin_TRAN_DATE" AS FLOAT)/"xbins_TRAN_DATE") + 1 AS INTEGER) 
END	AS "xbin_TRAN_DATE"
FROM	"universal_schema"."SALES_TRANSACTION"
,(
SELECT	MIN("SALES_TRAN_ID") AS "xmin_SALES_TRAN_ID"	,MAX("SALES_TRAN_ID") AS "xmax_SALES_TRAN_ID"	,MIN(10) AS "xwid_SALES_TRAN_ID"	,CAST(("xmax_SALES_TRAN_ID" - "xmin_SALES_TRAN_ID") / "xwid_SALES_TRAN_ID" AS INTEGER) + (
CASE	("xmax_SALES_TRAN_ID" - "xmin_SALES_TRAN_ID") MOD "xwid_SALES_TRAN_ID" 
	WHEN	0 THEN 0 
ELSE	1 
END	) AS "xbins_SALES_TRAN_ID"	,"xmin_SALES_TRAN_ID" + "xbins_SALES_TRAN_ID"*"xwid_SALES_TRAN_ID" AS "xnmax_SALES_TRAN_ID"	,MIN("TRAN_DATE") AS "xmin_TRAN_DATE"	,MAX("TRAN_DATE") AS "xmax_TRAN_DATE"	,MIN(5) AS "xwid_TRAN_DATE"	,CAST(("xmax_TRAN_DATE" - "xmin_TRAN_DATE") / "xwid_TRAN_DATE" AS INTEGER) + (
CASE	("xmax_TRAN_DATE" - "xmin_TRAN_DATE") MOD "xwid_TRAN_DATE" 
	WHEN	0 THEN 0 
ELSE	1 
END	) AS "xbins_TRAN_DATE"	,"xmin_TRAN_DATE" + "xbins_TRAN_DATE"*"xwid_TRAN_DATE" AS "xnmax_TRAN_DATE"	,CAST(COUNT(*) AS FLOAT) AS "xall"
FROM	"universal_schema"."SALES_TRANSACTION"
) A
) T2
WHERE	("T1"."xbin_SALES_TRAN_ID" = "T2"."xbin_SALES_TRAN_ID" 
	OR	("T1"."xbin_SALES_TRAN_ID" IS NULL 
	AND	"T2"."xbin_SALES_TRAN_ID" IS NULL)) 
	AND	("T1"."xbin_TRAN_DATE" = "T2"."xbin_TRAN_DATE" 
	OR	("T1"."xbin_TRAN_DATE" IS NULL 
	AND	"T2"."xbin_TRAN_DATE" IS NULL))
GROUP	BY 1,2,3,4,5,6,7,8,9
ORDER	BY 1,2,3,4,5,6,7,8,